import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux";
// import store from "@/redux/store";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ternak Syams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${manrope.variable} antialiased`}>{children}</body>
    </html>
  );
}
